export const predefinedKeywords = [
  {
    category: "General",
    keywords: [
      "Party",
      "Dance Party",
      "Sports",
      "Music",
      "Festival",
      "Concert",
      "Exhibition",
      "Workshop",
      "Tech Conference",
      "Networking",
      "Charity Event",
      "Fundraiser",
      "Community Gathering",
      "Book Reading",
      "Film Screening",
      "Theater",
      "Comedy Show",
      "Game Night",
      "Trivia Night",
      "Food Festival",
      "Wine Tasting",
    ],
  },
  {
    category: "Sports",
    keywords: [
      "Football",
      "Basketball",
      "Volleyball",
      "Tennis",
      "Golf",
      "Baseball",
      "Soccer",
      "Hockey",
      "Running",
      "Marathon",
      "Yoga",
      "Fitness Class",
      "Swimming",
      "Cycling",
      "Climbing",
      "Boxing",
      "MMA",
      "E-Sports",
      "Skateboarding",
      "Skiing",
      "Surfing",
    ],
  },
  {
    category: "Music & Entertainment",
    keywords: [
      "Rock",
      "Pop",
      "Classical",
      "Jazz",
      "Hip Hop",
      "Electronic",
      "DJ Night",
      "Karaoke",
      "Opera",
      "Live Band",
    ],
  },
  {
    category: "Art & Culture",
    keywords: [
      "Art Show",
      "Museum Tour",
      "Cultural Festival",
      "Photography Exhibition",
      "Painting Class",
      "Craft Workshop",
      "Poetry Slam",
    ],
  },
  {
    category: "Educational Events",
    keywords: [
      "Tech Talk",
      "Startup Pitch",
      "Hackathon",
      "Coding Workshop",
      "Webinar",
      "Science Fair",
      "Career Fair",
      "Leadership Seminar",
      "Book Club",
      "Public Lecture",
    ],
  },
  {
    category: "Family-Friendly",
    keywords: [
      "Kids Carnival",
      "Storytime",
      "Pet Show",
      "Holiday Event",
      "Parade",
      "Zoo Visit",
    ],
  },
  {
    category: "Outdoors & Adventure",
    keywords: [
      "Hiking",
      "Camping",
      "Nature Walk",
      "Bird Watching",
      "Beach Cleanup",
      "Stargazing",
    ],
  },
  {
    category: "Food & Drink",
    keywords: [
      "Cooking Class",
      "Baking Workshop",
      "Beer Tasting",
      "Food Truck Festival",
      "Farmers Market",
      "Vegan Festival",
      "BBQ Party",
    ],
  },
  {
    category: "Special Interest",
    keywords: [
      "Car Show",
      "Bike Show",
      "Anime Convention",
      "Cosplay Event",
      "Board Games",
      "Puzzle Room",
      "Magic Show",
      "Photography Walk",
    ],
  },
];
